# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Audio-Analyzer
version:      0.1
version_from: lib/Audio/Analyzer.pm
installdirs:  site
requires:
    Math::FFT:                     0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
